### ISSUE TITLE
Desenvolvedor(a) Front-End UI - São Paulo / SP

### ISSUE THREAD

**Issue by airroom** [BeeTech-global/bee-a-member#9]
<p align="center"><em>⚠️ <strong>OPA, ESPERA AÍ!</strong> Antes de prosseguir, conheça mais sobre a BeeTech e nossa área de Tech visitando o <a href="https://github.com/BeeTech-global/bee-a-member" target="_blank" title="Bee a Member"><strong>Bee a Member</strong></a></em>
</p>

---

## Descrição

Olá! Procuramos Fronts para atuarem junto à área de Marketing/Design auxiliando na criação de Landing Pages, email marketings e na manutenção do [Bee Pollen](https://github.com/BeeTech-global/bee-pollen), nosso doce Design System 🍯.

## Atribuições 

* Evolução técnica constante o/ _(💖 mostraremos o caminho 💖)_
* Criação/Manutenção de Landing Pages no HubSpot
* Criação/Manutenção de emails marketings e transacionais
* Manutenção de blogs em WordPress _(apenas HTML/CSS)_

## Requisitos

* Necessário cursar graduação em TI ou áreas relacionadas (pode até ser Design o/) e disponibilidade para estagiar 30 horas semanais de segunda a sexta.

### Habilidades necessárias 

_(Obviamente, não esperamos que você seja o Master of Puppets)_

* HTML
* CSS
* JavaScript/jQuery
* Noções de UX

### Habilidades que você aprenderá 🎓

* SASS
* Bootstrap
* GIT
* WordPress - basicão
* SEO
* +JavaScript/jQuery
* React

## Sumário
 
* Bolsa-auxílio: R$1.500,00 + VT R$440,00
* Local: Av Brigadeiro Faria Lima, 1355  - São Paulo / SP

### Muito bacana, muito legal. E agora?

Se, ANTES DE TUDO, seu coração palpitou com a nossa missão e cultura _(vide [Bee a Member](https://github.com/BeeTech-global/bee-a-member))_ e você curtiu o desafio, acesse este [Link](https://signup.kenoby.com/#/candidatos/me?position=5b52442d0a547a1a356f6708&tenant=5ac5085bd3a98b2b12beabff&jobsite=beetech&positionName=Est%C3%A1gio%20em%20Front-End%20/%20UI&applicantSource=&utm_source=) e inicie o processo o/

_*#LetPeopleBeeGlobal*_

**Comment by vinirossi** [comment]
Mandei!!! Obrigado @evansantos

**Comment by ahmatrai** [comment]
Me candidatei =)

**Comment by Roger-Melo** [comment]
Apenas presencial? =/

**Comment by airroom** [comment]
@Roger-Melo sim, apenas presencial :|

**Comment by yeltsinxyz** [comment]
Eu enviei, sou de Recife, mas se for aprovado no processo seletivo eu me realoco em 2 dias 😀

**Comment by brunooomelo** [comment]
Há vaga para voluntário? experiencia please.

**Comment by airroom** [comment]
@brunooomelo não temos uma posição sobre voluntariado, mas pfvr já envie o CV o/ Estudaremos essa possibilidade

**Comment by brunooomelo** [comment]
@airroom tem algum e-mail direto ou pelo link mesmo?

**Comment by airroom** [comment]
@brunooomelo Link mesmo o/

**Comment by brunooomelo** [comment]
beleza!! foi enviado.

**Comment by kvnol** [comment]
Não tenho a faculdade, mas queria me candidatar. =(

**Comment by airroom** [comment]
@kvnol na dúvida envia anyway o/
